### ISSUE TITLE
completions panic

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#116]
Step 1:
![image](https://user-images.githubusercontent.com/343840/136705873-2d21c0e2-7ab4-4118-8cef-81554b3bc478.png)
Step 2:
![image](https://user-images.githubusercontent.com/343840/136705884-2e22d289-a61a-46cf-820d-d33a08717a01.png)
```
1. cd C<tab>
2. it then shows cd .\
3. then type C<tab>, so the command line would then look like cd .\C, and that's where the crash happens
```

on windows

**Comment by onthebridgetonowhere** [comment]
This seems to work now, I would close it. @fdncred are you still having this issue?

**Comment by fdncred** [comment]
nope. thx!
