### ISSUE TITLE
Statements should autoview through table, even in blocks

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#291]
Comparing nushell and e-q, I noticed that currently e-q doesn't `echo` output the same way.

For example, something like this:
```
ls | each { echo hi; $it.name }
```
Will not display any of the "hi" messages for each of the rows. I'm not sure if they're being shown and drawn over or just not being shown, but it's worth investigating.

**Comment by aslynatilla** [comment]
According to the intended design, is `$it.name` evaluated before `echo` and then fed to it as an input `PipelineData` or should that evaluation be done by `echo`?

**Comment by jntrnr** [comment]
@aslynatilla - I thought more about this. I think the missing step might be that the pipeline isn't being run through `table` and then displayed. I don't think it's specific to `echo`, it's just where I think people will notice it.

I'll update the title.

**Comment by jntrnr** [comment]
This seems to be fixed now.
