### ISSUE TITLE
`math sum` doesn't support streams

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#299]
Looks like streams current assume that we're looking at a table. There are a couple other cases we should add. For example, if you have a stream of simpler values, it'd be nice to add those.

Something like:
```
[1] | each { $it } | math sum
```
cc @luccasmmg

**Comment by luccasmmg** [comment]
working on it

**Comment by luccasmmg** [comment]
```
〉[1 2] | each { $it } | math sum
3
```
Just fixed, any other examples that i should test before submiting the PR?

**Comment by jntrnr** [comment]
@luccasmmg - not that I saw. If we find more, we can always add them later no problem
