### ISSUE TITLE
Ranges tracking issue

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#35]
Collecting stuff to be implemented for ranges 

| done | description                            | example      | PR  |
| -    | -                                      | -            | -   |
| [x]  | Basic integer range                    | `0..10`      | #16 |
| [ ]  | Basic floating point range             | `0.0..10.0`  |     |
| [x]  | Right-exclusion                        | `0..<10`     | #16 |
| [ ]  | Left-unbounded range                   | `..10`       |     |
| [x]  | Right-unbounded range                  | `0..`        | #16  |
| [x]  | Do not allow totally-unbounded range   | `..`         | #16 |
| [x]  | Negative bounds                        | `-10..-2`    | #16 |
| [x]  | Stepping                               | `0..2..10`   | #43 |
| [x]  | Variables                              | `$a..10`     | #16 |
| [x]  | Subexpressions                         | `0..(8 + 2)` | #16 |
| [x]  | Reverse range                          | `10..0`      | #20 |
| [x]  | Correct syntax highlighting of all parts |              | #43  |

**Comment by jntrnr** [comment]
@kubouch is this done now?

**Comment by kubouch** [comment]
> @kubouch is this done now?

Yes!
