### ISSUE TITLE
Adding env var does not set host env var

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#356]
`let-env FOO = "bar"` sets the env var in the Stack but seems like it does not set it for the host. This probably breaks `ls_colors` which relies on the LS_COLORS env var, probably read from `std::env`.

The solution: Inside the `Stack::add_env_var()`, add the env var also into the host environment with `std::env`

Alternative: Make ls_colors (and any other cases where this is an issue) read Nushell's env var instead

**Comment by fdncred** [comment]
my vote is for everything the gets or sets environment variables to somewhere go through std::env.

**Comment by elferherrera** [comment]
Isn't that something that has already being discussed, that the host environment variables should not be touched

**Comment by kubouch** [comment]
Yeah, I think we should load all env vars to engine-q on startup, but then use *exclusively* the e-q's env vars. I already changed LS_COLORS to behave that way in the PR above, so I'll close this issue.
