### ISSUE TITLE
`register` allows the same command to be registered multiple times

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#377]
We should probably check for the existence of a command before registering it and perhaps check that the signature hasn't changed.

![Screen Shot 2021-11-28 at 3 11 12 PM](https://user-images.githubusercontent.com/343840/143786203-a4a91557-57e6-434c-aa79-d2200593dbe2.PNG)

**Comment by onthebridgetonowhere** [comment]
What happens now when you have multiple same commands registered? Which one is called?

**Comment by fdncred** [comment]
good question @onthebridgetonowhere . @elferherrera was this also fixed in your most recent PR?

**Comment by elferherrera** [comment]
The last one is called. Need to work on it to avoid duplication

**Comment by fdncred** [comment]
I believe @elferherrera fixed this.
