### ISSUE TITLE
Improve testing infrastructure for tables

### ISSUE THREAD

**Issue by stormasm** [nushell/engine-q#432]
This test should pass, but it fails...
If you drop this test into src/tests.rs you will notice it fails...

```rust
#[test]
fn command_filter_reject_4() -> TestResult {
    run_test(
        "[[lang, gems, grade]; [nu, 100, a]] | reject gems",
        "[{lang: nu, grade: a}]",
    )
}

```

**Comment by jntrnr** [comment]
@stormasm - I don't think we evaluate the expected source to get a value, so it wouldn't know the above was an expected table

**Comment by stormasm** [comment]
```rust

#[test]
fn command_filter_reject_5() -> TestResult {
    run_test(
        "[[lang, gems, grade]; [nu, 100, a]] | reject gems",
        "[[lang, grade]; [nu, a]]",
    )
}

```

**Comment by onthebridgetonowhere** [comment]
Is this something we still want to do, before merging?

**Comment by stormasm** [comment]
https://github.com/nushell/engine-q/pull/886

@onthebridgetonowhere thank you for pointing this out to me.
I am going ahead and closing the issue...
