### ISSUE TITLE
List with one value should auto-flatten to just the value

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#433]
Current:
```
> [1]
╭───┬───╮
│ 0 │ 1 │
╰───┴───╯
```

Expected:
```
> [1]
1
```

**Comment by jntrnr** [comment]
@kubouch - I think we should keep it the way we have it, though maybe the table is confusing?

We auto flatten in nu, but it creates bugs like how `1 | to json` and `[1] | to json` would be the same json but shouldn't be.

**Comment by kubouch** [comment]
True, let's keep it.
