### ISSUE TITLE
comments at the end of a line cause parsing errors

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#473]
things like this, with a comment at the end of a line will cause errors. if i remove the comments it parses fine.

`    let branch = ($gs | get branch) # Cyan`

<img width="560" alt="Screen Shot 2021-12-11 at 3 52 00 PM" src="https://user-images.githubusercontent.com/343840/145692726-f6cdcf0a-c0d8-4f89-87dd-28ef813af6dc.png">

**Comment by jntrnr** [comment]
@fdncred I can't seem to repro this with a smaller test case:

```
> 3 # test
3
```

I wonder if it's some combination of a few things to cause it

**Comment by jntrnr** [comment]
this one also seems to work okay:

```
> let branch = (3 + 4) # Cyan
```

**Comment by jntrnr** [comment]
repro'd:

```
(
  let foo = (3 + 4) # test
  let bar = ($foo * 10) # test
  $bar
)
```

**Comment by jntrnr** [comment]
theory: the subexpression parser will treat newlines as whitespace. We want this as a general rule, but still need a way for comments to end at the end of lines.

**Comment by fdncred** [comment]
if you look at the gist I sent you in discord, you'll see several ways this problem occurs. Just look for the lines that look like `# Cyan` or some other color and put it on the end of the next line. I think they're all inside `def blah [] { }` commands.

**Comment by jntrnr** [comment]
@fdncred I just realised my repro case actually isn't one (sub-expressions would require semicolons, which are missing). Do you have a small repro?

**Comment by fdncred** [comment]
this seems fixed now
