### ISSUE TITLE
zero cpu from `ps` command

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#481]
on my mac m1x i get 0 cpu while building nushell in a separate tab. the `sysinfo` crate may be broke or maybe our implementation based on this nushell thread https://github.com/nushell/nushell/issues/4142
<img width="1054" alt="Screen Shot 2021-12-12 at 8 18 08 PM" src="https://user-images.githubusercontent.com/343840/145742317-371c34ed-532d-485c-9e0d-cf6fe2df030d.png">

couldn't get `version | to md` to print out like the screenshot
<img width="853" alt="Screen Shot 2021-12-12 at 8 16 01 PM" src="https://user-images.githubusercontent.com/343840/145742179-5e9b8c5e-f846-4e69-afe4-969dafa40c87.png">

**Comment by jntrnr** [comment]
This also looks wrong on Windows:

![image](https://user-images.githubusercontent.com/547158/145754482-743d0629-0444-46c9-800d-c703f6f2b2eb.png)

(notice the virtual mem size also looking off)

**Comment by jntrnr** [comment]
Fixed by #484

**Comment by fdncred** [comment]
I'm not sure I'd call this working on my mac.
<img width="1237" alt="Screen Shot 2021-12-13 at 5 51 01 AM" src="https://user-images.githubusercontent.com/343840/145807427-02dce3ed-6794-45d8-ac92-f905b1e6d7d1.png">

vs ps
<img width="1232" alt="Screen Shot 2021-12-13 at 5 52 27 AM" src="https://user-images.githubusercontent.com/343840/145807673-04fd2187-720d-4a5a-b292-eb2eac5f1f7f.png">

vs htop
<img width="1239" alt="Screen Shot 2021-12-13 at 5 52 56 AM" src="https://user-images.githubusercontent.com/343840/145807704-ddc0311b-53d3-4470-b84a-ebfe78715e6a.png">

**Comment by jntrnr** [comment]
@fdncred - I'm not sure if the current method is going to be able to see all the 0.1 and 0.2 level activity that top does. imho this might be a limitation of sysinfo (the crate we're using for doing `ps`)

**Comment by rbpatt2019** [comment]
I feel like I'm just commenting on issues here recently, but I see similar behaviour on my Intel MacBook Pro - `htop` reports docker and zoom using approximately 9% of my CPU each at the moment, but `ps` in `engine-q` fails to detect either as using CPU - it lists them as 0%. Interestingly, as I was typing this, it did (briefly) detect zoom as running...and using 6010.1% of my cpu! 

Sorry for all the noise! I recently discovered engine-q/nushell and love it! If I can contribute in any way, I'd be happy to - but my knowledge of rust is limited, to say the least.

**Comment by jntrnr** [comment]
@rbpatt2019 - I've updated the `ps` command to hopefully be a little more accurate. Would you mind trying it again?

**Comment by rbpatt2019** [comment]
@jntrnr Whatever you did there worked! My output now matches `top`, so this can be considered closed from my end! Really appreciate it, and looking forward to the `engine-q` merge.

**Comment by fdncred** [comment]
yup - works on my m1 as well
![image](https://user-images.githubusercontent.com/343840/149531589-0c17e26c-577f-4506-a354-05c8800075c3.png)

however, the `status` column is broken on windows.

**Comment by onthebridgetonowhere** [comment]
@fdncred - I would close this issue for now and we should open another one if we want to fix the `status` problem you mentioned.
