### ISSUE TITLE
duplicate path entries

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#483]
in the screenshot i show fish path and then immediately show engine-q path which has a duplicate first entry. jt confirmed this wasn't happening on windows. i'm on mac. i've seen this on nushell a long time ago but the difference was a case difference between the duplicates. that doesn't appear to be the issue here.

path in `fish` shell and split from `engine-q`
![image](https://user-images.githubusercontent.com/343840/145742740-ad6b583f-c507-48bd-b376-9a2ad8f6a859.png)

path in `engine-q` - just the string (note the first two are dupes)
```
〉$nu.env.PATH
/Users/fdncred/.cargo/bin:/Users/fdncred/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

version info
<img width="853" alt="Screen Shot 2021-12-12 at 8 16 01 PM" src="https://user-images.githubusercontent.com/343840/145742766-a17f4788-6021-4ca7-a3f3-fe7284c80f15.png">

**Comment by kubouch** [comment]
The PATH with duplicate entries is already fetched from `std::env`. I tried printing the env vars from [this loop](https://github.com/nushell/engine-q/blob/e9525627e68a153f66447367978b7bf3a9b1ff57/src/main.rs#L242) and it showed duplicates. Seems like something sets the PATH in the environment _before_ engine-q is launched.

**Comment by fdncred** [comment]
really, what is going on here? why would `std::env::vars()` be returning duplicates in PATH? here's some debug logging that I did printing out the same line.
```rust
        for (k, v) in std::env::vars() {
            eprintln!("env2: k: {} v: {}", &k, &v);
            stack.add_env_var(k, v);
        }
```

```
env2: k: LC_TERMINAL v: iTerm2
env2: k: LC_TERMINAL_VERSION v: 3.5.0beta3
env2: k: LOGNAME v: fdncred
env2: k: LaunchInstanceID v: F814A3D4-5DA9-4C97-806C-F9245F3DB5A1
env2: k: PATH v: /Users/fdncred/.cargo/bin:/Users/fdncred/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
env2: k: PWD v: /Users/fdncred/src/forks/engine-q
env2: k: RUSTUP_HOME v: /Users/fdncred/.rustup
env2: k: RUSTUP_TOOLCHAIN v: stable-aarch64-apple-darwin
```

**Comment by fdncred** [comment]
oh wait - look at this. when running with this command, I get something different. NO DUPES

`> cargo b --features=extra`
`> target/debug/engine-q`


```
env2: k: USER v: fdncred
env2: k: ITERM_SESSION_ID v: w0t0p0:CF6556CD-E03E-4C86-A2DE-23D77CFF1160
env2: k: PATH v: /Users/fdncred/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
env2: k: HOMEBREW_PREFIX v: /opt/homebrew
env2: k: COLORTERM v: truecolor
```

**Comment by kubouch** [comment]
Seems like `cargo run` is just prepending `~/.cargo/bin` to the path for some reason... Maybe to ensure all the cargo tools are avaliable?

**Comment by fdncred** [comment]
agreed. I think I'm going to close it since we know where it's coming from now.
