### ISSUE TITLE
`lines` drops empty lines

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#491]
On Linux (the cat from git bash on Windows has other issues and won't demonstrate this properly):
```
>  cat ./crates/nu-protocol/src/value/mod.rs
... see empty lines

> cat ./crates/nu-protocol/src/value/mod.rs | lines
... see empty lines filtered out
```

I think `lines` should still preserve empty lines.

**Comment by jntrnr** [comment]
Yeah, we could flip the default and make `lines` keep the empty lines by default and have a flag like `--skip-empty` to skip the empty lines.

**Comment by onthebridgetonowhere** [comment]
We can probably close this!

**Comment by jntrnr** [comment]
@onthebridgetonowhere sounds good
