### ISSUE TITLE
Get Columns of a Table

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#510]
In Nushell, to get the list of table columns, you do `ls | get`. This doesn't work in engine-q.

IMO, we should not port `get` without arguments to return the columns since that is not intuitive. Instead, we could have a separate `columns` command, for example.

**Comment by fdncred** [comment]
100% agree about get. also like `ls | columns` but I also wonder if there's some shorthand we could use. I'm not sure what that shorthand would be. Another idea is to modify `table` since I think this is where the columns are coming from like `ls | table -c`?

**Comment by onthebridgetonowhere** [comment]
I like the idea of having a command for getting the columns of a table. I think we could have both, `columns` as a separate command and a shorthand for `table`. One note though, not sure `table` is finalized yet, so maybe we can start with having a separate command for now. I'd be happy to give it a try, if we agree to have a `columns` command.

**Comment by onthebridgetonowhere** [comment]
Oh, I see that @stormasm already added it in #519. Shall we close this?

**Comment by stormasm** [comment]
yes this should be closed @kubouch or @fdncred can close it I believe...

**Comment by fdncred** [comment]
yup. good work!
