### ISSUE TITLE
to auto-flatten or not to auto-flatten

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#533]
Nushell auto-flattens so you can do this command and get a list of every parameter.

```
> $nu.lang | get signature
```

With engine-q I have not figured out how to do this simple task. Here is a list of the ones I've tried.

`$scope.commands | get 0 | get signature` works for 1 command
`$scope.commands | get signature | flatten` doesn't work
`$scope.commands | each {|r| $r | get $r.signature}` doesn't work
`$scope.commands | each {|r| $r.signature}` doesn't work
`$scope.commands | select signature` doesn't work
`$scope.commands.signature | select command parameter_name parameter_type syntax_shape is_optional short_flag description` doesn't work
`$scope.commands | flatten signature` doesn't work
`scope.commands | each {|r| ($r | get signature).0 }` doesn't list all the params
`$scope.commands | each {|r| ($r | get signature) } | get 220` doesn't get all the commands, of course
`$scope.commands | each {|r| ($r | get signature) }` gets all of them but they're in tables and not flattened
`$scope.commands | each {|r| ($r | get signature) } | each {|s| $s | get parameter_name}` gets the parameter name but they're in a list and not flattened

imo, this needs to be fixed. it shouldn't be so difficult.

**Comment by kubouch** [comment]
I'd say, rather than auto-flatten, `flatten` should be modified so that `$scope.commands.signature | flatten` works.

**Comment by fdncred** [comment]
yup #534 fixed it. `$scope.commands | get signature | flatten` works and `$scope.commands.signature | flatten` works
