### ISSUE TITLE
`table` command produces a cell with a table when used with `ls`

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#566]
<img width="682" alt="Screen Shot 2021-12-23 at 3 59 16 PM" src="https://user-images.githubusercontent.com/343840/147295338-8dcd6cd0-ff32-4529-8d82-90afa4099d2a.png">

**Comment by jntrnr** [comment]
This appears to be coming from us lacking StringStream, so we're getting a stream of a string and treating that stream like a table rather than strings to be printed to the screen.

**Comment by jntrnr** [comment]
(fwiw, I have a draft of a PR I was working on in hopes of fixing this)

**Comment by jntrnr** [comment]
this seems to be fixed now
