### ISSUE TITLE
Prompt command does not work correctly with newlines

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#575]
(Linux) If I end my prompt line with a new line, the start of the line gets offset where the previous line ended.

Consider this definition:
```
> def build-prompt [] {
    [ 'foo' 'bar' (char nl)] | str collect
}

> $"'(build-prompt)'"
'foobar
'

> let-env PROMPT_COMMAND = { build-prompt }

foobar 
      >
```

Notice how the `>` is offset even though I would expect it to be at the beginning of the line.

**Comment by jntrnr** [comment]
I think this is because we're in raw mode. We could translate `\n` to `\r\n` for the user, or let them know they should do it

**Comment by kubouch** [comment]
This is quite unexpected IMO. I think `char nl` should be translated on every system to mean "move to a new line and put the cursor at the beginning". That is probably the 99.999% use case for a newline. We could add options to `char` to enter these two separately if necessary.

Is there a way to work around this currently?

**Comment by jntrnr** [comment]
thinking about this a bit more - why are we in raw mode when we're printing out to the screen?

I think this might be a reedilne bug where we're not disabling raw mode when printing the prompt and user input.

**Comment by lukexor** [comment]
Not sure if this is related, but attempting to use the current `starship` prompt results in an extra newline I can't quite get rid of.

The top instance is on first starting engine-q - You can see the default `PROMPT_INDICATOR_VI_INSERT` overwrote the timestamp prompt from starship. Pressing enter fixes it, but leaves the cursor one line further down then it should be.

<img width="414" alt="Screen Shot 2022-01-22 at 2 36 01 PM" src="https://user-images.githubusercontent.com/709609/150657606-e55eaf47-bf03-4059-9022-f3754c5bc01a.png">

**Comment by lukexor** [comment]
Also if I try this:

```
let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS | decode utf8 | str trim -r -c (char nl) }
```

I can get rid of the newline, but it throws the cursor way off to the right

<img width="497" alt="Screen Shot 2022-01-22 at 2 54 40 PM" src="https://user-images.githubusercontent.com/709609/150658004-560e77fa-55bd-4221-82e1-53bd468d4d7c.png">

**Comment by kubouch** [comment]
@lukexor `... | decode utf-8 | str trim` does not work?

Also what operating system are you in?

**Comment by lukexor** [comment]
No it doesn't. str trim seems to have no effect. Adding just the decode results in that screenshot with cursor being on the expected line, but shifted to the right.

Without decode, it's correctly all left aligned, but cursor is one line lower than expected.

Os is macOS. If I disable line breaks in starship entirely, the cursor still ends up one line lower than expected. I suspect that the trailing Unicode or nerdfont character starship uses for the prompt character is the culprit

**Comment by lukexor** [comment]
Looking more, the line_break module in starship just emits a "\n". By itself this works fine and acts like "\r\n", but including it as-is in $env.PROMPT_COMMAND results in an unwanted trailing newline, which seems like engine-q is adding

If you `decode utf8`, it works as expected but the linebreak acts like a plain "\n" without the carriage return, resulting in an unexpected right shifted prompt line. Possibly a work around could be to decode and replace the "\n" with a "\r\n"

**Comment by jntrnr** [comment]
this might be a reedline issue. I think it should convert `\n` to `\r\n` when in raw mode and printing strings to the screen.

**Comment by lukexor** [comment]
I believe it does? It's only when passed through decode that it doesn't which is only required because I haven't figured out what's causing the trailing crlf at the very end of the starship prompt. Is there anything special happening in prompt parsing when an external command is called to produce the prompt string?

**Comment by lukexor** [comment]
Interesting. In debugging this, the following results:

```
let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS | decode utf8 | str find-replace -a (char newline) (char crlf) }

prompt.render_prompt_left() = "\r\n\u{1b}[1;36m~/dev/engine-q\u{1b}[0m on \u{1b}[1;35m\u{e0a0} main\u{1b}[0m \u{1b}[1;31m[!]\u{1b}[0m is \u{1b}[1;38;5;208m📦 v0.1.0\u{1b}[0m via \u{1b}[1;31m🦀 v1.58.1 \u{1b}[0m\r\n\u{1b}
[1;33m[07:59]\u{1b}[0m "
```
crlf and working as expected.

```
# Per the docs/3rd_Party_Prompts.md recommendations:
let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS | decode utf8 | str collect }

prompt.render_prompt_left() = "\n\u{1b}[1;36m~/dev/engine-q\u{1b}[0m on \u{1b}[1;35m\u{e0a0} main\u{1b}[0m \u{1b}[1;31m[!]\u{1b}[0m is \u{1b}[1;38;5;208m📦 v0.1.0\u{1b}[0m via \u{1b}[1;31m🦀 v1.58.1 \u{1b}[0m\n\u{1b}[1;3
3m[08:01]\u{1b}[0m "
```
newline only, and the second line doesn't get a carriage return properly as expected since we're in raw mode.

```
# Per existing starship nushell install recommendations (extracted from starship init since it still relies on $nu.env):
let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS }

prompt.render_prompt_left() = ""
```
The prompt DOES appear, but render_prompt_left is empty. Not important to this issue, but in the following I have my PROMPT_INDICATOR_VI_INSERT set to `(version) ❯`

<img width="423" alt="Screen Shot 2022-01-25 at 8 08 35 AM" src="https://user-images.githubusercontent.com/709609/151014086-98e6829d-1b67-4b31-a4aa-4a5e969a6fd0.png">

**Comment by lukexor** [comment]
I figured out the last use case. Because `let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS }` results in the external command being the `last_expression` - `run_external` ignores it's stdout which means that the returned ByteStream from the command is empty, and thus when being collected into a string results in an empty string.

Is that intended behavior for the last_expression of a block?

**Comment by fdncred** [comment]
@lukexor heads-up. JT just pushed this change that may affect your prompt https://github.com/nushell/engine-q/pull/871. I'm playing with it now and it looks like this is working for me.
`let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS | str find-replace -a (char nl) (char crlf) }`

**Comment by jntrnr** [comment]
@fdncred - there's also a change from @sholderbach coming in soon (if it's not already there) that might also remove the need for that `str find-replace` call

**Comment by sholderbach** [comment]
Gotta handle the prompt strings as well in nushell/reedline#281... brb

**Comment by lukexor** [comment]
Thanks @fdncred. Yeah I had a working prompt using that method. Nice to be able to pull all the decodes and crlf stuff out soon though! Great work.

**Comment by fdncred** [comment]
I think these are the latest recommendations.

**starship**
`let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS | str collect | str trim }`

**oh-my-posh**
`let-env PROMPT_COMMAND = { oh-my-posh --config $"($env.POSH_THEMES_PATH)/blue-owl.omp2.json" | str trim }`

**Comment by lukexor** [comment]
`let-env PROMPT_COMMAND = { starship prompt --cmd-duration $env.CMD_DURATION_MS | str collect }` seems to work as well. The extra `str trim` requires a leading space in `PROMPT_INDICATOR`

**Comment by fdncred** [comment]
> 

oh. good point. i do have `' '` for `PROMPT_INDICATOR` on my configuration.

There's a new change coming. https://github.com/nushell/engine-q/pull/874 should auto-trim.
