### ISSUE TITLE
`cd -` 

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#577]
Calling `cd -` does not throw an error.

I think we don't have the `cd -` functionality implemented. I would expect an error about `-` directory not found. Instead, it silently does nothing.

I think it would be nice to have this functionality -- we could have `PWD` and `OLD_PWD` env vars. Calling `cd <path>` would move `PWD` into `OLD_PWD` and `<path>` into `PWD`. Calling `cd -` would swap `PWD` and `OLD_PWD`. We might as well go fancy and have `PWD` as a list or a record to implement this logic but that's probably stretching it too far.

**Comment by fdncred** [comment]
I haven't looked but `cd -` is in nushell. I wonder how it works there.

**Comment by kubouch** [comment]
I think in Nushell we store the previous pwd in the shell manager or something like that.

**Comment by jntrnr** [comment]
fixed by #787
