### ISSUE TITLE
Variable not found in custom command signature

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#578]
Seems like the variable symbol lookup in command signatures does not work properly.

```
> def print-me [x] { $x }

> let d = '/foo/bar'

> print-me $d
Error: nu::shell::variable_not_found (https://docs.rs/nu-protocol/0.1.0/nu-protocol/enum.ShellError.html#variant.VariableNotFoundAtRuntime)

  × Variable not found
   ╭─[entry #5:1:1]
 1 │ printme $d
   ·         ─┬
   ·          ╰── variable not found
   ╰────
```

The order of defining `d` and `print-me` does not matter.

It seems to work for built-in variables: Both `print-me $nu.env.PATH` and `print-me $config` work fine

**Comment by kubouch** [comment]
I think what's happening is that the variable capturing is somehow broken. The `print-me` command block captures only the `$x` variable with ID 21. When passing `$d` with ID 19 on the third line, the engine sees only ID 21 in the block captures and reports an error.

**Comment by fdncred** [comment]
yup, I've run into this problem too porting and writing e-q scripts. I have a prompt script that I've been working on for a few weeks and I've not getting anywhere with it.

**Comment by kubouch** [comment]
I've narrowed it down a little bit. When parsing the `print-me $d` call, the `positional` argument at this line https://github.com/nushell/engine-q/blob/a811eee6b86978d175e02b89c7f334a9bf5a9b24/crates/nu-parser/src/parser.rs#L572 reports ID 21 (`$x`) but the result of this line https://github.com/nushell/engine-q/blob/a811eee6b86978d175e02b89c7f334a9bf5a9b24/crates/nu-parser/src/parser.rs#L581 reports ID 19 (`$d`) which gets pushed into the actual call that is passed to the engine.

**Comment by kubouch** [comment]
I'm wondering if we should just change the ID19 to match the ID 21

**Comment by kubouch** [comment]
It seems to be a problem only for custom commands. Existing e-q commands accept the variable just fine.

**Comment by kubouch** [comment]
Seems like the block captures are parsed correctly, but at this line https://github.com/nushell/engine-q/blob/a811eee6b86978d175e02b89c7f334a9bf5a9b24/crates/nu-protocol/src/engine/stack.rs#L70 it does not find the variable so it is not get added onto the stack.
