### ISSUE TITLE
`PWD` env var and native `pwd` diverge after calling `cd`

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#585]
```
> cd  # go the to home directory

> $nu.env.PWD
/home/kubouch

> pwd  # native command 
/home/kubouch

> do { cd .. }

> $nu.env.PWD
/home/kubouch

> pwd
/home
```

**Comment by jntrnr** [comment]
@kubouch - is still broken for you with the latest e-q? I can't seem to repro

**Comment by kubouch** [comment]
This should be fixed by the PWD scoping changes.

**Comment by fdncred** [comment]
The only difference I see here, other than it works now, is that, on Mac:
```
pwd = /home/fdncred
$env.PWD = /home/fdncred/
```
I'm wondering if we should trim the trailing slash or not?
