### ISSUE TITLE
Multi-line pipelines do not work anymore

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#603]
Splitting a pipeline into multiple lines does not work anymore. Consider these three scripts:

```
# script1.nu
ls
| str upcase name
```

```
# script2.nu
ls |
str upcase name
```

```
# script3.nu
ls | str upcase name
```

A couple of days ago, `script1.nu` worked just fine for me. Now, both `script1.nu` and `script2.nu` first run `ls`, then throw
```
Error: nu::shell::incompatible_path_access (https://docs.rs/nu-protocol/0.1.0/nu-protocol/enum.ShellError.html#variant.IncompatiblePathAccess)

  × Data cannot be accessed with a cell path
   ╭─[test_pipe.nu:1:1]
 1 │ ls |
 2 │ str upcase name
   ·            ──┬─
   ·              ╰── nothing doesn't support cell paths
   ╰────
```

It must have been some recent PR that broke it.

**Comment by jntrnr** [comment]
Of these three, I think technically only the third one was valid under the nushell parser rules. To get either one or two, you'd need to wrap in parens.

**Comment by kubouch** [comment]
I think the second one worked in Nushell. I really dig the first one and was happy to see it in e-q. Is there a way to bring it back? Or would it reintroduce some problems you fixed in the last PRs?

**Comment by jntrnr** [comment]
@kubouch - can you `git bisect` and see where it got changed? If we know when it changed, maybe we can fix it?

**Comment by kubouch** [comment]
OK, I'll try to investigate!

**Comment by jntrnr** [comment]
I'm seeing this now too. I'm pretty sure this used to work:

```
〉do {
::: open ./README.md |
::: lines |
::: length
::: }
```

But now it doesn't. You can compare vs putting the whole pipeline on a line

**Comment by jntrnr** [comment]
this appears to be fixed now
