### ISSUE TITLE
colour of list slightly wrong

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#645]
![image](https://user-images.githubusercontent.com/547158/147872884-8c681959-e07e-44d3-b7eb-d083c5b5a0ae.png)

**Comment by fdncred** [comment]
I think this is fixed, not sure why pr didn't close it.

**Comment by fdncred** [comment]
oh, wait. #646 isn't landed yet. I'm not seeing this issue.

**Comment by jntrnr** [comment]
This should be fixed now with the slightly better highlighting
