### ISSUE TITLE
colour of table is slightly wrong

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#647]
![image](https://user-images.githubusercontent.com/547158/147873376-0b90b984-ae51-462d-aaae-268a016a660d.png)

**Comment by fdncred** [comment]
I'm not seeing this issue either.

**Comment by jntrnr** [comment]
@fdncred - it's suspiciously the same as the indicator, which makes me wonder if that's coming from a missing ansi reset from reedline or something

**Comment by fdncred** [comment]
ya, good point. we may have ansi-leak there in reedline.

**Comment by fdncred** [comment]
it sure looks like ansi-leak but this code looks like it's calling reset.
https://github.com/nushell/reedline/blob/a2682b50f949245b5933471992b8094e1b3ae478/src/painter.rs#L250
