### ISSUE TITLE
Performance regression with `let-env` and `it` in an iterator

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#649]
Running `benchmark { echo 1..100000 | each { let-env x = 4; $it + 10 } | length }` is much slower in e-q than in Nushell.
* engine-q: **~2.4 s**
* Nushell: **~700 ms**

It seems to be the combination of using both `let-env` and `$it` since both `benchmark { echo 1..100000 | each { let-env x = 4 } | length }` and `benchmark { echo 1..100000 | each { $it + 10 } | length }` is faster in engine-q.

**Comment by jntrnr** [comment]
caused by "Flush stmts (#584)"

My guess - we're doing stdout writes even if the pipeline hands us a `$nothing`. Seeing if I can fix that
