### ISSUE TITLE
Make `fetch` part of "extra"

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#661]
I think right now you need to do `--all-features` to get everything including `fetch`. Should make `fetch` part of extra.

**Comment by onthebridgetonowhere** [comment]
I'll take a look at this tonight and do some cleanup for fetch.

**Comment by onthebridgetonowhere** [comment]
We decided to make `fetch` a default command envisioning future uses of `fetch` for auto downloading things that we might need. We can probably close this issue when #664 is merged.
