### ISSUE TITLE
when a command is accepted with enter, hints should go away.

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#669]
notice the dark gray hint from a previous command in the history. also notice that the command has already been accepted and executed with enter. once a command has been accepted/executed by hitting enter, the hint should go away. on the positive side, the accepted command is added to the history correctly.

<img width="1028" alt="Screen Shot 2022-01-04 at 6 38 09 PM" src="https://user-images.githubusercontent.com/343840/148143143-1dffa780-3e26-4555-837c-577bf6078fff.png">

**Comment by jntrnr** [comment]
I think this one should probably go in the reedline repo. The hinting I think is all done there.

**Comment by fdncred** [comment]
move to here https://github.com/nushell/reedline/issues/239

**Comment by sholderbach** [comment]
Solved by nushell/reedline#250 in reedline. Will be fixed with the next reedline bump including https://github.com/nushell/reedline/commit/b6f47f020a92ee5c1e1ae1c8a2f30d6fe448e517

**Comment by fdncred** [comment]
thanks @sholderbach
