### ISSUE TITLE
PATH not working anymore

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#683]
After this PR https://github.com/nushell/engine-q/pull/682 running executables from PATH does not work anymore. I seems like it's because the externals are always auto-expanded to cwd but sometimes they need to be fetched from PATH.

I think this is the moment we need to bring in `which`.

**Comment by jntrnr** [comment]
@kubouch I wonder if we should check if it looks like an executable or a path to an executable. We don't want to expand the first one but we do for the second.

**Comment by fdncred** [comment]
related, we may also want to bring in the `is_executable()` over from nushell eventually.
