### ISSUE TITLE
`def` optional parameters, long & short parameters, help messages for parameters

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#689]
I was testing out #530 while porting my weather script to engine-q.

This works great.
```
def foo [x?:int] {
  if $x != $nothing {
    $x + 10
  } else {
    5
  }
}
```

But while trying to emulate that with multiple parameters I couldn't get it to work. I'm not sure if it's the `?`, the spacing, the parameter delimiter, the comments, the long(short) params, so I tried a bunch of different things.

I've tried these:

space comma space between params
update: works 🎉 
```
def foo3 [l?:int , u?:string] {
  let is_l = ($l == $nothing)
  let is_u = ($u == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```

comma space between params
update: works 🎉 
```
def foo3 [l?:int, u?:string] {
  let is_l = ($l == $nothing)
  let is_u = ($u == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```

just space between params
update: works 🎉 
```
def foo3 [l?:int u?:string] {
  let is_l = ($l == $nothing)
  let is_u = ($u == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```

params on separate lines
update: works 🎉 
```
def foo3 [
l?:int
u?:string
] {
  let is_l = ($l == $nothing)
  let is_u = ($u == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```

params on separate lines with a comma
update: works 🎉 
```
def foo3 [
l?:int,
u?:string
] {
  let is_l = ($l == $nothing)
  let is_u = ($u == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```

params on separate lines with parameter help messages
update: works 🎉 
```
def foo3 [
l?:int # some param
u?:string # some other param
] {
  let is_l = ($l == $nothing)
  let is_u = ($u == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```

and what i really wanted to work, which was the first try
long(short) params, separate lines, param help messages

update: still does not work with `$l` or `$locIdx` 😢 maybe it's not supposed to work this way?
```
def foo3 [
--locIdx?(-l): int # The location id 0-3
--units?(-u): string # The units "f" or "c"
] {
  let is_l = ($l == $nothing)
  let is_u = ($u == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```

all give this error 
update: this is still true - you can't call the ones that work above like `foo -l 3 -u "C"` 😢 maybe it's not supposed to work this way?
```
> foo3 -l
Error: nu::parser::unknown_flag (link)

  × The `foo3` command doesn't have flag `-l`.
   ╭─[entry #97:1:1]
 1 │ foo3 -l
   ·       ┬
   ·       ╰── unknown flag
   ╰────
  help: use foo3 --help for a list of flags
```
clearly i'm missing something fundamental because the `foo` example works.

added 1/22/22
```
def foo3 [
--locIdx?(-l): int # The location id 0-3
--units?(-u): string # The units "f" or "c"
] {
  let is_l = ($locIdx == $nothing)
  let is_u = ($units == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```
I want to call like any of the following:
1. `foo3 -l 0 -u c`
2. `foo3 -l 1`
3. `foo3 -u f`
4. `foo3 --locIdx 3 --units c`
5. `foo3 --locIdx 2`
6. `foo3 --units f`

# Working Example (tested with 6 tests above)

note: there's not optional indicator `?` on these parameters, which is a little confusing. I guess they're optional by default?

```
def foo3 [
 --locIdx(-l): int # The location id 0-3
 --units(-u): string # The units "f" or "c"
 ] {
   let is_l = ($locIdx == $nothing)
   let is_u = ($units == $nothing)
   $"l is ($is_l) locIdx [($locIdx)], u is ($is_u) units [($units)]"
 }
```

**Comment by jntrnr** [comment]
All of the positional parameter test seem to work okay for me. Was there any other code involved outside of the example?

**Comment by jntrnr** [comment]
@fdncred - can you try these again with the latest e-q and see if you still see them?

**Comment by fdncred** [comment]
@jntrnr i updated the issue above with an `update` line.

**Comment by fdncred** [comment]
need to circle back eventually and perhaps give a better error message that `?` isn't required for things like this.

```
def foo3 [
--locIdx?(-l): int # The location id 0-3
--units?(-u): string # The units "f" or "c"
] {
  let is_l = ($locIdx == $nothing)
  let is_u = ($units == $nothing)
  $"l is ($is_l), u is ($is_u)"
}
```
but for now, let's close it and move on.
