### ISSUE TITLE
`ls <relative path>` gives absolute path filenames

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#694]
if you do `ls crates` in the e-q directory, instead of getting small, relative paths we currently are getting the full absolute path filenames

**Comment by onthebridgetonowhere** [comment]
The easiest would be to make `short_names` flag `true` in the `if path.is_dir() ` block.  (https://github.com/nushell/engine-q/blob/main/crates/nu-command/src/filesystem/ls.rs#L79) However, this will only show the filename or the folder name and not the parent folder.
