### ISSUE TITLE
compare bool for inequality

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#699]
seems odd that we can't do this. `if $true != $true { $true }`
![image](https://user-images.githubusercontent.com/343840/148569432-c50be246-1841-4c1f-bf20-7f06324be07c.png)

i tried to `change bool to bool` but it didn't work - haha!

i guess i could say `if $true == $false` but that's no fun.

**Comment by onsah** [comment]
Can I take this one?

**Comment by jntrnr** [comment]
@onsah - yup!

**Comment by onsah** [comment]
@jntrnr Here is the [PR](https://github.com/nushell/engine-q/pull/709). I made the fix but there are some questions because I am not familiar with the project :)
