### ISSUE TITLE
need to figure out zombie plugins

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#708]
now that I'm using plugins regularly with my prompt (gstat), I've noticed lots of zombie plugin processes. we need to figure out how to exit properly from plugins and communicate the exit to the parent process.

<img width="515" alt="Screen Shot 2022-01-09 at 7 48 57 AM" src="https://user-images.githubusercontent.com/343840/148685065-0f656db0-45ad-479e-828d-e0440a8dcc92.png">

**Comment by jntrnr** [comment]
I see a new zombie every time I hit enter, so it seems to be tied to how the plugin is exiting as we create the prompt.

**Comment by fdncred** [comment]
there's a lot of good information on the web about zombie processes. it boils down to the parent process that spawns the plugin is waiting for the plugin's exit status and the plugin isn't returning it to the parent - or something like that.

the screenshot above in the issue is created from using the oh-my.nu script with the git_prompt.

**Comment by jntrnr** [comment]
Fixed by #901
