### ISSUE TITLE
Feature Request: Key Bindings

### ISSUE THREAD

**Issue by stormasm** [nushell/engine-q#719]
Right arrow is full hint completion nushell/reedline#244

It would be great if the end user could have the ability...

**_to make TAB the full hint completion instead of Right arrow..._**

Personally for me on my macbook pro keyboard the tab is a much
easier keystroke to complete than the right arrow which is far way
in the right side of my keyboard where as TAB is right there and quick...

And everyone has a different preference so with that in mind...

This is an example of something that ideally would be configurable.

**Comment by fdncred** [comment]
@stormasm is this resolved?

**Comment by stormasm** [comment]
@fdncred I am happy to test this now...

But have been holding off because I am still not sure how to set it...

With so many changes in how config works recently...

**_to make TAB the full hint completion instead of Right arrow..._**

If you would kindly (if you know) tell me the magic spell / I put in my
config file to get this going / test it...

Thank you.

**Comment by stormasm** [comment]
@fdncred I am happy to test this now...

But have been holding off because I am still not sure how to set it...

With so many changes in how config works recently...

**_to make TAB the full hint completion instead of Right arrow..._**

If you would kindly (if you know) tell me the magic spell / I put in my
config file to get this going / test it...

Thank you.

**Comment by fdncred** [comment]
i haven't tried yet but i think you have to do something like this in the keybindings sections of the config.nu. the key is finding what to put in modifier, keycode, mode, and event. also, whether it's a send or an edit event

```
    { 
      name: complete_hint
      modifier: none
      keycode: tab
      mode: emacs
      event: { send: historyhintcomplete }
    }
```

**Comment by stormasm** [comment]
@fdncred ok cool gracias !

I am heading out now for a few hours and will be back later,
and will hopefully test it this evening or in the morning...

**Comment by stormasm** [comment]
@fdncred great news it works --- thanks kindly for your recipe --- which is what I put in mine

```rust
  keybindings: {
    name: complete_hint
    modifier: none
    keycode: tab
    mode: emacs
    event: {send: historyhintcomplete }
   }
```
