### ISSUE TITLE
External commands do not work after capture fix

### ISSUE THREAD

**Issue by kubouch** [nushell/engine-q#726]
After #723 I can no longer spawn external commands.

To reproduce:
```
> git status

  × External command
   ╭─[entry #1:1:1]
 1 │ git status
   · ─┬─
   ·  ╰── No such file or directory (os error 2)
   ╰────
```

**Comment by fdncred** [comment]
This is from windows. the error looks like `git` isn't in your path.
![image](https://user-images.githubusercontent.com/343840/149222980-84d94b16-03cb-4df1-b39f-37e52e50a3b4.png)

**Comment by kubouch** [comment]
It happens with any command. In the commit before the capture fix, everything works.

**Comment by fdncred** [comment]
i wonder if it's a linux/mac thing only because it's working fine on windows. i'll test mac in a little while.
/cc @jntrnr

**Comment by jntrnr** [comment]
@kubouch what platform are you on?

I'll take a look soon

**Comment by kubouch** [comment]
@jntrnr Linux. It seems like the env->string translation is not working properly. My translated PATH looks like `[path1:path2]`,

**Comment by jntrnr** [comment]
```
│ 40 │ PATH                     │ list<unknown> │ [list 11 items]                                            │ /home/jt/.cargo/bin:/home/jt/.cargo/bin:/usr/local/sbin:/u │
│    │                          │               │                                                            │ sr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr │
│    │                          │               │                                                            │ /local/games:/snap/bin 
```

```
let config = {
    env_conversions: {
            "PATH": {
                from_string: { |s| $s | split row ':' }
                to_string: { |v| $v | str collect ':' }
            }
            "LS_COLORS": {
                from_string: { |s| $s | split row ':' }
                to_string: { |v| $v | str collect ':' }
            }
            "DYLD_FALLBACK_LIBRARY_PATH": {
                from_string: { |s| $s | split row ':' }
                to_string: { |v| $v | str collect ':' }
            }
    }
}
```

**Comment by kubouch** [comment]
It seems to be related to my `export env PATH { [ ... list ... ] }` I'm doing in the config. Without setting the env in the config, the conversion works fine. Also, when I change my definition to `export env PATH { [ ... list ... ] | str collect ':' }`, it works fine. 

Probably related to https://github.com/nushell/engine-q/issues/687. We need to sit down and work down the order what happens  to env translation of env vars that are defined in the config. It's strange it worked before the PR, though.

**Comment by kubouch** [comment]
My config looks like:
```
# init.nu

export def build-config [] {
    {
        env_conversions: {
            "PATH": {
                from_string: { |s| $s | split row (char env_sep) | path expand }
                to_string: { |v| $v | str collect (char env_sep) }
            }
        }
}

export env PATH {
    $env.PATH | split row (char env_sep) |
    prepend [
        ~/.cargo/bin
        ~/.fzf/bin
        ~/.go/bin
        ~/miniconda3/bin
        ~/miniconda3/condabin
        ~/.local/bin
        ~/.local/usr/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/local/cuda/bin
        /opt/cuda/bin
        /usr/lib/jvm/default/bin
        /usr/bin/site_perl
        /usr/bin/vendor_perl
        /usr/bin/core_perl
        /usr/bin
    ] | path expand | uniq 
}
```
```
# config.nu

use ~/.config/nushell/init.nu *
let config = build-config
```

It works when I put `| str collect (char_sep)` after the last line in the `export env PATH` block. Before the PR it worked without.

**Comment by jntrnr** [comment]
@kubouch - this also works for me. I'm wondering if something else in the config might be breaking and you're seeing it show up in the path maybe?

**Comment by kubouch** [comment]
This is the weirdest thing ever. Consider the example above. Then add 
```
export env FOO_PWD { pwd | decode utf-8 }  # pwd is external since we don't have our own yet
```

Then, launching e-q _**sometimes**_ triggers this error on startup:
```
  × External command
    ╭─[~/.config/nushell/init2.nu:12:1]
 12 │
 13 │ export env FOO_PWD { pwd | decode utf-8 }
    ·                      ─┬─
    ·                       ╰── No such file or directory (os error 2)
 14 │
    ╰────
```

Often, the error does not appear. Usually, I need to launch e-q a couple of times in a rapid succession for it to trigger. With my bigger config, it triggers every time.

When the error triggers, my translated PATH has the surrounding `[]`. Without the error, the path is translated to a string correctly.

This is really mysterious. Looks like some kind of race condition.

**Comment by jntrnr** [comment]
Still no luck. I've tried both in debug and release mode to see if one of them has a timing issue somehow.

Does debug or release seem to cause it more often?

**Comment by jntrnr** [comment]
Trying to think of other things it might be - what version of rustc do you use?

**Comment by kubouch** [comment]
It seems to behave both on debug and release the same

**Comment by kubouch** [comment]
stable-x86_64-unknown-linux-gnu 1.57.0

**Comment by jntrnr** [comment]
I'm stumped... no idea what's happening. Maybe you can put some logging things in to see where the environment is set wrong on startup? Not sure how even to debug this

**Comment by kubouch** [comment]
My hunch would be the `run_external` command where we spawn the externals in a separate thread. That's the only place for a race condition I can think of. Maybe the command is sometimes spawned before the translation is finished or something like that.

**Comment by kubouch** [comment]
Here is what I found: The exports from a module are stored as a hash map. The `use` command then iterates through the env vars and runs their blocks, but because of the hash map, the order is undefined.

If I rewrite the `use` command in `config.nu` as a sequence of `let-env`, we end up having two scenarios:
```
# case 1
# config.nu

let-env FOO_PWD = (pwd | decode utf-8)
let-env PATH = ([ ... ] | path expand | uniq)
let config = build-config
```
or
```
# case 2
# config.nu

let-env PATH = ([ ... ] | path expand | uniq)
let-env FOO_PWD = (pwd | decode utf-8)
let config = build-config
```

In the first case, the PATH has not been set up yet -- the only PATH we see is a string inherited from the host process => FOO_PWD assignment works.

In the second case, the PATH is a List type, **but**, we don't have `$config.env_conversions` set up yet: that happens on line 3. Therefore, the env->string translation cannot happen. What is sent to the `pwd` external command is the default string fallback which in the case of a list looks like `[path1:path2:...]` (note the surrounding []).

The solution has two parts:
1. Use `IndexMap` for module exportables (the Overlay struct) for a predictable env evaluation order.
2. Rewrite the config so that `$config` is established before setting environment variables.

I'm wondering if there is something we can do to help diagnose errors with missing env var conversions in the config. But at least making the evaluation order deterministic would help a lot.
