### ISSUE TITLE
Allow for specifying modes for keybindings

### ISSUE THREAD

**Issue by rosshadden** [nushell/engine-q#727]
Currently with nushell's rustyline functionality it is not possible to assign keybindings to specific modes. I started a discussion of this functionality [here](https://github.com/nushell/nushell/discussions/4252), and was asked to create an issue here in engine-q, where this kind of thing would eventually belong.

In the current keybinding.yml workflow you can make mappings, but as there is no way to specify a mode they all apply to the default (insert) mode. Thus you are unable to map anything to common letters that would be typed as part of normal shell interaction.

**Comment by jntrnr** [comment]
I think this is now possible. @elferherrera would need to confirm

**Comment by elferherrera** [comment]
@rosshadden The keybinding functionality added provides modes like emacs, vi normal and vi insert. I don't know if those are the modes you are mentioning

**Comment by rosshadden** [comment]
Yes those are the modes I am talking about. The current nushell functionality only lets you define mappings that work in insert mode, not in vi normal.

**Comment by fdncred** [comment]
@rosshadden can we close this since the functionality exists in e-q?

**Comment by rosshadden** [comment]
Yeah, thanks
