### ISSUE TITLE
debugging scripts is very difficult

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#739]
Without the use of `echo something | autoview` or a command like `print stderr ($blah) some thing` it's not easy to debug scripts.

**Comment by jntrnr** [comment]
you can't use `echo something`?

**Comment by fdncred** [comment]
I still need to test this more. it may be fixed.

**Comment by fdncred** [comment]
ok, this is mostly fixed and works well. however, I'm puzzled because I've had to remove all my `(char nl)` commands in an effort to stop double printing new lines.

**Comment by fdncred** [comment]
closing this debugging issue since you can do `echo blah` and it works mostly like nushell's autoview.
