### ISSUE TITLE
Command parsing consumes special characters (ripgrep regex for example)

### ISSUE THREAD

**Issue by lukexor** [nushell/engine-q#819]
Version: 564c2dd

Expected behavior (Works in nushell):

```
> ifconfig en0 | rg 'inet (\d+.\d+.\d+.\d+)'
inet 192.168.0.6 netmask 0xffffff00 broadcast 192.168.0.255
```

Actual behavior:

No output.

Notes:

I've yet to be able to find any regex that works in engine-q - for example, the following works in nushell. It doesn't matter if it's a piped command or not.

```
ifconfig | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}'
grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' file
```

**Comment by fdncred** [comment]
I was able to get this to work in e-q.
`ifconfig en0 | rg 'inet [0-9]{1,3}+.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}'`

**Comment by fdncred** [comment]
confirmed that this does NOT work on windows now.
`ipconfig | rg '(\d+.\d+.\d+.\d+)'`

This does however, kind of - it returns but ipv6 ips are in it, so e-q works, regex needs some work.
`ipconfig | rg '([0-9]{1,3}+.){4}'`

**Comment by jntrnr** [comment]
@fdncred so are you thinking we don't need to escape in Windows either?

**Comment by fdncred** [comment]
for fun, this is one that doesn't use `\` and still work on windows `ipconfig | rg '(25[0-5][.]|(2[0-4]|1[0-9]|[1-9]|)[0-9][.]){3}(25[0-5][.]|(2[0-4]|1[0-9]|[1-9]|)[0-9])'`

**Comment by jntrnr** [comment]
There's a fix for this that snuck into #820. Does the latest main help at all?

**Comment by fdncred** [comment]
> 

It's working for me in windows.

**Comment by jntrnr** [comment]
I'll go ahead and close. @lukexor if you're still seeing it, please feel free to reopen
