### ISSUE TITLE
Unable to implicitly run .cmd files in path

### ISSUE THREAD

**Issue by jmoore34** [nushell/engine-q#820]
This works in nu but not currently in engine-q, as shown below:
![image](https://user-images.githubusercontent.com/1783464/150656521-d9e78179-2eb3-4010-b95b-80bc82db8c12.png)

-----------
Second example:
![image](https://user-images.githubusercontent.com/1783464/150656446-3a62ce7a-6dc1-479f-92d4-6fe68000c8b5.png)

**Comment by fdncred** [comment]
I just ran into this and it's friggin annoying. :)

**Comment by jntrnr** [comment]
fixed by #902
