### ISSUE TITLE
syntax_highlight causes panic

### ISSUE THREAD

**Issue by lukexor** [nushell/engine-q#859]
Version: `04395ee`

```
~/dev/pix-engine on  main [$?] is 📦 v0.5.4 via 🦀 v1.58.1
[17:46] 0.1.0 ❯ { thread 'main' panicked at 'byte index 18446744073709543046 is out of bounds of `{ k`', crates/nu-cli/src/syntax_highlight.rs:41:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

All I typed was `{ k` and it panicked. I was attempting to type an `each { kill $it.pid }`

**Comment by jntrnr** [comment]
@lukexor - I'm not able to repro with these steps. Hmm, I wonder what might be different. I'm using a different prompt and am on linux mint, but neither of those in theory should mess with the spans like that. Hmm, not sure

**Comment by lukexor** [comment]
Let me see if I can get more details on it.

**Comment by lukexor** [comment]
It's because I had an alias `alias k = kubectl`. Removing it fixes the issue. Running `which` on it returns no results but `locate` shows it as being in `/usr/local/bin/kubectl`

**Comment by jntrnr** [comment]
I have a different repro but might be the same root cause:

```
> alias g = git
> { g }
> <up arrow to get previous history>
```

**Comment by fdncred** [comment]
oh ya, I think aliases are broken again. #771, #770, #702, #620

**Comment by jntrnr** [comment]
They're tricky to get right :upside_down_face: 

I suspect we aren't going to be able to use the `span` helper function that merges spans for us. Since these might come from aliases, we have to be super careful not to create spans that don't actually exist in the file cache.

**Comment by jntrnr** [comment]
I think what I'll do instead is harden the highlighter. We still need to do more work on how aliases expand, and it'll probably require a bit of a rewrite of that part of the parser and associated AST. For now, let's at least not crash.
