### ISSUE TITLE
right arrow during completions is completing hint

### ISSUE THREAD

**Issue by jntrnr** [nushell/engine-q#879]
I think we want things like right arrow to be focused on the task the user is doing. I noticed that when completions pop up the right arrow takes the hint and then if you hint right again you move around the completion list. When the completion list is up, we probably don't want to accept the hint and instead just move around the completions.

cc @sholderbach / @elferherrera

**Comment by elferherrera** [comment]
That is a good idea. As far as I remember the hinter is off when a menu is active

**Comment by elferherrera** [comment]
found the culprit. This [PR](https://github.com/nushell/reedline/pull/284) should fix this
