### ISSUE TITLE
inconsistent behavior with the `$nothing` symbol

### ISSUE THREAD

**Issue by fdncred** [nushell/engine-q#893]
I've seen this in several places but sometimes `nothing` is represented with nothing and sometimes it uses the nothing symbol of a green x. It would be good to be consistent. Here's one example. The first table has the emoji. The last table does not.

```
    ~/s/f/engine-q  open Cargo.toml | get bin 
╭───┬───────────────────┬───────────────────────────────────────┬───────────────────╮
│ # │       name        │                 path                  │ required-features │
├───┼───────────────────┼───────────────────────────────────────┼───────────────────┤
│ 0 │ nu_plugin_inc     │ src/plugins/nu_plugin_core_inc.rs     │ [list 1 item]     │
│ 1 │ nu_plugin_example │ src/plugins/nu_plugin_core_example.rs │ [list 1 item]     │
│ 2 │ nu_plugin_gstat   │ src/plugins/nu_plugin_extra_gstat.rs  │ [list 1 item]     │
│ 3 │ engine-q          │ src/main.rs                           │ ❎                │
├───┼───────────────────┼───────────────────────────────────────┼───────────────────┤
│ # │       name        │                 path                  │ required-features │
╰───┴───────────────────┴───────────────────────────────────────┴───────────────────╯
    ~/s/f/engine-q  open Cargo.toml | get bin | get required-features  
╭───┬───────────────╮
│ 0 │ [list 1 item] │
│ 1 │ [list 1 item] │
│ 2 │ [list 1 item] │
│ 3 │               │
╰───┴───────────────╯
```

**Comment by kubouch** [comment]
It is related to this change: https://github.com/nushell/engine-q/pull/860

That converts the empty value to $nothing to prevent the missing column error. In the first case, the value is not there at all (it's not even $nothing) so that's why there is the icon.

**Comment by fdncred** [comment]
I thought that was the purpose of the emoji, to show where `$nothing` was? I guess you're saying that the emoji represents empty/null/non-existing values, and nothing is represented with Value::Nothing. I'm not sure how I feel about that.

**Comment by jntrnr** [comment]
@fdncred - the emoji was more for "missing", which is different than nothing. 

`[{ name: foo, x: 3 }, { name: bar}]` <- this would have the emoji, since `x` is missing in the second row.

`[{ name: foo, x: 3 }, { name: bar, x: $nothing}]` <- this wouldn't have the emoji

**Comment by fdncred** [comment]
ok, i understand now. I guess we need to make that clear in the documentation because it's confused me until today.
